import { createServer } from "node:http";
import type { FullConfig } from "@playwright/test";

export const MOCK_PORT = 9876;

const CONTAINERS = [
  {
    Id: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
    Names: ["/plex"],
    Image: "plexinc/pms-docker:latest",
    ImageID: "sha256:abc001",
    Created: 1700000000,
    State: "running",
    Status: "Up 14 days",
    Labels: {
      "dash.title": "Plex",
      "dash.category": "Media",
      "dash.icon": "plex",
      "dash.description": "Media server",
      "traefik.enable": "true",
      "traefik.http.routers.plex.rule": "Host(`plex.homelab.local`)",
    },
  },
  {
    Id: "b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3",
    Names: ["/jellyfin"],
    Image: "jellyfin/jellyfin:latest",
    ImageID: "sha256:abc002",
    Created: 1700000100,
    State: "running",
    Status: "Up 12 days",
    Labels: {
      "dash.title": "Jellyfin",
      "dash.category": "Media",
      "dash.icon": "jellyfin",
      "dash.description": "Free media system",
      "traefik.enable": "true",
      "traefik.http.routers.jellyfin.rule": "Host(`jellyfin.homelab.local`)",
    },
  },
  {
    Id: "c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4",
    Names: ["/sonarr"],
    Image: "linuxserver/sonarr:latest",
    ImageID: "sha256:abc003",
    Created: 1700000200,
    State: "running",
    Status: "Up 10 days",
    Labels: {
      "dash.title": "Sonarr",
      "dash.category": "Media",
      "dash.icon": "sonarr",
      "dash.description": "TV series manager",
      "traefik.enable": "true",
      "traefik.http.routers.sonarr.rule": "Host(`sonarr.homelab.local`)",
    },
  },
  {
    Id: "d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5",
    Names: ["/radarr"],
    Image: "linuxserver/radarr:latest",
    ImageID: "sha256:abc004",
    Created: 1700000300,
    State: "running",
    Status: "Up 10 days",
    Labels: {
      "dash.title": "Radarr",
      "dash.category": "Media",
      "dash.icon": "radarr",
      "dash.description": "Movie collection manager",
      "traefik.enable": "true",
      "traefik.http.routers.radarr.rule": "Host(`radarr.homelab.local`)",
    },
  },
  {
    Id: "e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6",
    Names: ["/lidarr"],
    Image: "linuxserver/lidarr:latest",
    ImageID: "sha256:abc005",
    Created: 1700000400,
    State: "running",
    Status: "Up 9 days",
    Labels: {
      "dash.title": "Lidarr",
      "dash.category": "Media",
      "dash.icon": "lidarr",
      "dash.description": "Music collection manager",
      "traefik.enable": "true",
      "traefik.http.routers.lidarr.rule": "Host(`lidarr.homelab.local`)",
    },
  },
  {
    Id: "f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1",
    Names: ["/readarr"],
    Image: "linuxserver/readarr:develop",
    ImageID: "sha256:abc006",
    Created: 1700000500,
    State: "exited",
    Status: "Exited (1) 2 hours ago",
    Labels: {
      "dash.title": "Readarr",
      "dash.category": "Media",
      "dash.icon": "readarr",
      "dash.description": "Ebook collection manager",
      "traefik.enable": "true",
      "traefik.http.routers.readarr.rule": "Host(`readarr.homelab.local`)",
    },
  },
  {
    Id: "a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8",
    Names: ["/overseerr"],
    Image: "sctx/overseerr:latest",
    ImageID: "sha256:abc007",
    Created: 1700000600,
    State: "running",
    Status: "Up 8 days",
    Labels: {
      "dash.title": "Overseerr",
      "dash.category": "Media",
      "dash.icon": "overseerr",
      "dash.description": "Request management for Plex",
      "traefik.enable": "true",
      "traefik.http.routers.overseerr.rule": "Host(`requests.homelab.local`)",
    },
  },
  {
    Id: "b8c9d0e1f2a3b8c9d0e1f2a3b8c9d0e1f2a3b8c9",
    Names: ["/grafana"],
    Image: "grafana/grafana:latest",
    ImageID: "sha256:abc008",
    Created: 1700001000,
    State: "running",
    Status: "Up 20 days",
    Labels: {
      "dash.title": "Grafana",
      "dash.category": "Monitoring",
      "dash.icon": "grafana",
      "dash.description": "Metrics and dashboards",
      "traefik.enable": "true",
      "traefik.http.routers.grafana.rule": "Host(`grafana.homelab.local`)",
    },
  },
  {
    Id: "c9d0e1f2a3b4c9d0e1f2a3b4c9d0e1f2a3b4c9d0",
    Names: ["/prometheus"],
    Image: "prom/prometheus:latest",
    ImageID: "sha256:abc009",
    Created: 1700001100,
    State: "running",
    Status: "Up 20 days",
    Labels: {
      "dash.title": "Prometheus",
      "dash.category": "Monitoring",
      "dash.icon": "prometheus",
      "dash.description": "Time series metrics",
      "traefik.enable": "true",
      "traefik.http.routers.prometheus.rule":
        "Host(`prometheus.homelab.local`)",
    },
  },
  {
    Id: "d0e1f2a3b4c5d0e1f2a3b4c5d0e1f2a3b4c5d0e1",
    Names: ["/uptime-kuma"],
    Image: "louislam/uptime-kuma:latest",
    ImageID: "sha256:abc010",
    Created: 1700001200,
    State: "running",
    Status: "Up 15 days",
    Labels: {
      "dash.title": "Uptime Kuma",
      "dash.category": "Monitoring",
      "dash.icon": "uptime-kuma",
      "dash.description": "Status and uptime monitoring",
      "traefik.enable": "true",
      "traefik.http.routers.uptime-kuma.rule": "Host(`status.homelab.local`)",
    },
  },
  {
    Id: "e1f2a3b4c5d6e1f2a3b4c5d6e1f2a3b4c5d6e1f2",
    Names: ["/portainer"],
    Image: "portainer/portainer-ce:latest",
    ImageID: "sha256:abc011",
    Created: 1700002000,
    State: "running",
    Status: "Up 30 days",
    Labels: {
      "dash.title": "Portainer",
      "dash.category": "Infrastructure",
      "dash.icon": "portainer",
      "dash.description": "Container management",
      "traefik.enable": "true",
      "traefik.http.routers.portainer.rule": "Host(`portainer.homelab.local`)",
    },
  },
  {
    Id: "f2a3b4c5d6e7f2a3b4c5d6e7f2a3b4c5d6e7f2a3",
    Names: ["/authentik"],
    Image: "ghcr.io/goauthentik/server:latest",
    ImageID: "sha256:abc012",
    Created: 1700002100,
    State: "running",
    Status: "Up 28 days",
    Labels: {
      "dash.title": "Authentik",
      "dash.category": "Infrastructure",
      "dash.icon": "authentik",
      "dash.description": "Identity provider",
      "traefik.enable": "true",
      "traefik.http.routers.authentik.rule": "Host(`auth.homelab.local`)",
    },
  },
  {
    Id: "a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4",
    Names: ["/traefik"],
    Image: "traefik:latest",
    ImageID: "sha256:abc013",
    Created: 1700002200,
    State: "running",
    Status: "Up 30 days",
    Labels: {
      "dash.hide": "true",
    },
  },
  {
    Id: "b4c5d6e7f8a9b4c5d6e7f8a9b4c5d6e7f8a9b4c5",
    Names: ["/watchtower"],
    Image: "containrrr/watchtower:latest",
    ImageID: "sha256:abc014",
    Created: 1700002300,
    State: "running",
    Status: "Up 30 days",
    Labels: {
      "dash.hide": "true",
    },
  },
  {
    Id: "c5d6e7f8a9b0c5d6e7f8a9b0c5d6e7f8a9b0c5d6",
    Names: ["/vaultwarden"],
    Image: "vaultwarden/server:latest",
    ImageID: "sha256:abc015",
    Created: 1700003000,
    State: "running",
    Status: "Up 25 days",
    Labels: {
      "dash.title": "Vaultwarden",
      "dash.category": "Productivity",
      "dash.icon": "vaultwarden",
      "dash.description": "Password manager",
      "traefik.enable": "true",
      "traefik.http.routers.vaultwarden.rule": "Host(`vault.homelab.local`)",
    },
  },
  {
    Id: "d6e7f8a9b0c1d6e7f8a9b0c1d6e7f8a9b0c1d6e7",
    Names: ["/nextcloud"],
    Image: "nextcloud:latest",
    ImageID: "sha256:abc016",
    Created: 1700003100,
    State: "running",
    Status: "Up 5 days (unhealthy)",
    Labels: {
      "dash.title": "Nextcloud",
      "dash.category": "Productivity",
      "dash.icon": "nextcloud",
      "dash.description": "File sync and share",
      "traefik.enable": "true",
      "traefik.http.routers.nextcloud.rule": "Host(`cloud.homelab.local`)",
    },
  },
  {
    Id: "e7f8a9b0c1d2e7f8a9b0c1d2e7f8a9b0c1d2e7f8",
    Names: ["/home-assistant"],
    Image: "ghcr.io/home-assistant/home-assistant:stable",
    ImageID: "sha256:abc017",
    Created: 1700004000,
    State: "running",
    Status: "Up 18 days",
    Labels: {
      "dash.title": "Home Assistant",
      "dash.category": "Home",
      "dash.icon": "home-assistant",
      "dash.description": "Home automation",
      "traefik.enable": "true",
      "traefik.http.routers.home-assistant.rule": "Host(`ha.homelab.local`)",
    },
  },
  {
    Id: "f8a9b0c1d2e3f8a9b0c1d2e3f8a9b0c1d2e3f8a9",
    Names: ["/node-red"],
    Image: "nodered/node-red:latest",
    ImageID: "sha256:abc018",
    Created: 1700004100,
    State: "exited",
    Status: "Exited (0) 30 minutes ago",
    Labels: {
      "dash.title": "Node-RED",
      "dash.category": "Home",
      "dash.icon": "node-red",
      "dash.description": "Flow-based programming",
      "traefik.enable": "true",
      "traefik.http.routers.node-red.rule": "Host(`nodered.homelab.local`)",
    },
  },
  {
    Id: "a9b0c1d2e3f4a9b0c1d2e3f4a9b0c1d2e3f4a9b0",
    Names: ["/pihole"],
    Image: "pihole/pihole:latest",
    ImageID: "sha256:abc019",
    Created: 1700005000,
    State: "running",
    Status: "Up 22 days",
    Labels: {
      "dash.title": "Pi-hole",
      "dash.category": "Network",
      "dash.icon": "pi-hole",
      "dash.description": "DNS-level ad blocking",
      "traefik.enable": "true",
      "traefik.http.routers.pihole.rule": "Host(`pihole.homelab.local`)",
    },
  },
];

const ROUTERS = [
  {
    name: "plex@docker",
    rule: "Host(`plex.homelab.local`)",
    service: "plex@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "jellyfin@docker",
    rule: "Host(`jellyfin.homelab.local`)",
    service: "jellyfin@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "sonarr@docker",
    rule: "Host(`sonarr.homelab.local`)",
    service: "sonarr@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "radarr@docker",
    rule: "Host(`radarr.homelab.local`)",
    service: "radarr@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "lidarr@docker",
    rule: "Host(`lidarr.homelab.local`)",
    service: "lidarr@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "readarr@docker",
    rule: "Host(`readarr.homelab.local`)",
    service: "readarr@docker",
    status: "disabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "overseerr@docker",
    rule: "Host(`requests.homelab.local`)",
    service: "overseerr@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "grafana@docker",
    rule: "Host(`grafana.homelab.local`)",
    service: "grafana@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "prometheus@docker",
    rule: "Host(`prometheus.homelab.local`)",
    service: "prometheus@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "uptime-kuma@docker",
    rule: "Host(`status.homelab.local`)",
    service: "uptime-kuma@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "portainer@docker",
    rule: "Host(`portainer.homelab.local`)",
    service: "portainer@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "authentik@docker",
    rule: "Host(`auth.homelab.local`)",
    service: "authentik@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "vaultwarden@docker",
    rule: "Host(`vault.homelab.local`)",
    service: "vaultwarden@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "nextcloud@docker",
    rule: "Host(`cloud.homelab.local`)",
    service: "nextcloud@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "home-assistant@docker",
    rule: "Host(`ha.homelab.local`)",
    service: "home-assistant@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "node-red@docker",
    rule: "Host(`nodered.homelab.local`)",
    service: "node-red@docker",
    status: "disabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
  {
    name: "pihole@docker",
    rule: "Host(`pihole.homelab.local`)",
    service: "pihole@docker",
    status: "enabled",
    using: ["websecure"],
    tls: {},
    entryPoints: ["websecure"],
  },
];

const SERVICES = [
  {
    name: "plex@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.2:32400": "UP" },
  },
  {
    name: "jellyfin@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.3:8096": "UP" },
  },
  {
    name: "sonarr@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.4:8989": "UP" },
  },
  {
    name: "radarr@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.5:7878": "UP" },
  },
  {
    name: "lidarr@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.6:8686": "UP" },
  },
  { name: "readarr@docker", status: "disabled", serverStatus: {} },
  {
    name: "overseerr@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.7:5055": "UP" },
  },
  {
    name: "grafana@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.8:3000": "UP" },
  },
  {
    name: "prometheus@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.9:9090": "UP" },
  },
  {
    name: "uptime-kuma@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.10:3001": "UP" },
  },
  {
    name: "portainer@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.11:9000": "UP" },
  },
  {
    name: "authentik@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.12:9000": "UP" },
  },
  {
    name: "vaultwarden@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.13:80": "UP" },
  },
  {
    name: "nextcloud@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.14:80": "DOWN" },
  },
  {
    name: "home-assistant@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.15:8123": "UP" },
  },
  { name: "node-red@docker", status: "disabled", serverStatus: {} },
  {
    name: "pihole@docker",
    status: "enabled",
    serverStatus: { "http://172.17.0.16:80": "UP" },
  },
];

export default async function globalSetup(_config: FullConfig) {
  const server = createServer((req, res) => {
    const url = new URL(req.url ?? "/", `http://localhost:${MOCK_PORT}`);
    res.setHeader("Content-Type", "application/json");
    res.setHeader("Access-Control-Allow-Origin", "*");

    if (url.pathname.startsWith("/containers/json")) {
      res.writeHead(200);
      res.end(JSON.stringify(CONTAINERS));
    } else if (url.pathname === "/api/http/routers") {
      res.writeHead(200);
      res.end(JSON.stringify(ROUTERS));
    } else if (url.pathname === "/api/http/services") {
      res.writeHead(200);
      res.end(JSON.stringify(SERVICES));
    } else {
      res.writeHead(404);
      res.end("{}");
    }
  });

  await new Promise<void>((resolve, reject) => {
    server.listen(MOCK_PORT, "127.0.0.1", resolve);
    server.once("error", reject);
  });

  return async () => {
    await new Promise<void>((resolve) => server.close(() => resolve()));
  };
}
