widgets:
  - type: host-stats
    size: medium

  - type: host-chart
    metric: load # load | memory
    size: large

  - type: host-chart
    metric: memory # load | memory
    size: large

  - type: host-stat-uptime
    size: small
  - type: host-stat-load
    size: small
  - type: host-stat-memory
    size: small
